using System;

public enum EventDefine
{
    BATTLE,

    //card
    BATTLE_CARD_START_FORWARD,
    BATTLE_CARD_STOP_FORWARD,

    BATTLE_CARD_START_FLY,
    BATTLE_CARD_STOP_FLY,
    BATTLE_CARD_ATTACK_END,

    BATTLE_CARD_CLICKED,

    SKILL_PROJECTILE_FLY_COMPLETE,

    UI_HE_TI_PROMPT_UI_TOUCHED,
    UI_COPY_START_PROMPT_UI_TOUCHED,
    UI_COPY_END_PROMPT_UI_TOUCHED,

    BATTLE_FORWARD_BTN_CLICKED,
    BATTLE_ACCLERATE_BTN_CLIKED,
    BATTLE_AUTO_FORWARD_BTN_CLIKED,
	BATTLE_QUIT_BTN_CLICK,
}
